// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UdemyAPI.Persistence.Contexts;

#nullable disable

namespace UdemyAPI.Persistence.Migrations
{
    [DbContext(typeof(UdemyDbContext))]
    partial class UdemyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UdemyAPI.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ce49619-a6b5-4e59-804f-8208efe5feb4"),
                            CategoryName = "Yazılım",
                            CreatedDate = new DateTime(2024, 9, 10, 11, 57, 22, 217, DateTimeKind.Utc).AddTicks(5360),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("0066fe1c-9330-4c83-bd51-9b8d4dd7f5d5"),
                            CategoryName = "Finans",
                            CreatedDate = new DateTime(2024, 9, 10, 11, 57, 22, 217, DateTimeKind.Utc).AddTicks(5380),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("5762830f-ab85-47b0-aaa7-29564b14948f"),
                            CategoryName = "Kişisel Gelişim",
                            CreatedDate = new DateTime(2024, 9, 10, 11, 57, 22, 217, DateTimeKind.Utc).AddTicks(5382),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("UdemyAPI.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("UdemyAPI.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LessonVideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("UdemyAPI.Domain.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7fa13f3-bb17-4394-ad88-f8874088bf58"),
                            About = "Test",
                            CreatedDate = new DateTime(2024, 9, 10, 11, 57, 22, 217, DateTimeKind.Utc).AddTicks(6982),
                            ImageUrl = "testurl",
                            IsDeleted = false,
                            NameSurname = "Gencay Yildiz"
                        },
                        new
                        {
                            Id = new Guid("d8191d49-63fb-4d5a-b5cf-9d62cd7e8340"),
                            About = "Test2",
                            CreatedDate = new DateTime(2024, 9, 10, 11, 57, 22, 217, DateTimeKind.Utc).AddTicks(6994),
                            ImageUrl = "testurl",
                            IsDeleted = false,
                            NameSurname = "Murat Yucedag"
                        },
                        new
                        {
                            Id = new Guid("d294c65c-db60-43b7-8527-24e79cb5391d"),
                            About = "Test3",
                            CreatedDate = new DateTime(2024, 9, 10, 11, 57, 22, 217, DateTimeKind.Utc).AddTicks(6995),
                            ImageUrl = "testurl",
                            IsDeleted = false,
                            NameSurname = "Maximillian Shwarzmuller"
                        });
                });

            modelBuilder.Entity("UdemyAPI.Domain.Entities.Course", b =>
                {
                    b.HasOne("UdemyAPI.Domain.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UdemyAPI.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Courses")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("UdemyAPI.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("UdemyAPI.Domain.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("UdemyAPI.Domain.Entities.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("UdemyAPI.Domain.Entities.Course", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("UdemyAPI.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
